#
# CsharpDatabase Hook
#

# Travis language: c(sharp)
language: c

# Mono
install:
 - sudo apt-get install mono-devel mono-dmcs

env:
 matrix:
  - ./build.sh
  - ./build.sh debug

# Only watch the master branch
branches:
  only:
    - master

# Notify if needed
notifications:
  irc:
    channels:
      - "irc.rizon.net#schumix2"
