#
# CsharpDatabase Hook
#

# Travis language: c(sharp)
language: c

# Mono
install:
 - sudo apt-get install cmake mono-devel mono-gmcs

script:
 - ./build.sh release

# Only watch the master branch
branches:
  only:
    - master

# Notify if needed
notifications:
  irc:
    channels:
      - "irc.rizon.net#schumix"
